<?php

namespace AppBundle\Repository;

/**
 * DishCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DishCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
