<?php

namespace AppBundle\Repository;

/**
 * DishCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DishCategoryRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Get all child categories of a DishCategory
     *
     * @param int $categoryId
     * @return array
     */
    public function getChildCategoryId($categoryId)
    {
        $query = $this->createQueryBuilder('h')
            ->select('h.categoryId', 'h.name')
            ->where('h.categoryId = :categoryId')
            ->orWhere('h.parent = :categoryId')
            ->setParameter('categoryId', $categoryId)
            ->getQuery();
        return $query->getResult();
    }
}
