<?php

namespace AppBundle\Repository;

/**
 * HasRatedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HasRatedRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRecipeAverageRating($recipeId)
    {
        $query = $this->createQueryBuilder('h')
            ->select("avg(h.rating) as rating_avg, count(h.rating) as rating_count")
            ->where('h.recipe = :id')
            ->setParameter(':id', $recipeId)
            ->getQuery();

        return $query->getResult();
    }
}
