<?php

namespace AppBundle\Repository;

/**
 * HasRatedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HasRatedRepository extends \Doctrine\ORM\EntityRepository
{
}
