<?php

namespace AppBundle\Repository;

/**
 * RecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeRepository extends \Doctrine\ORM\EntityRepository
{
    public function lastVerifiedRecipes()
    {
        $query = $this->createQueryBuilder('h')
            ->join('h.author', 'd')
            ->where('d.isVerified = :isVerified')
            ->setParameter('isVerified', 1)
            ->addOrderBy('h.publishedDate', 'DESC')
            ->setMaxResults(3)
            ->getQuery();
        return $query->getResult();
    }

    public function orderByPublishedDate()
    {
        $query = $this->createQueryBuilder('h')
            ->addOrderBy('h.publishedDate', 'DESC')
            ->getQuery();
        return $query->getResult();
    }

    public function mostPopular()
    {

    }
}
