<?php

namespace AppBundle\Repository;

/**
 * RecipeHasDishCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeHasDishCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
