<?php

namespace AppBundle\Repository;

/**
 * RecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeRepository extends \Doctrine\ORM\EntityRepository
{
    public function lastVerifiedRecipes()
    {
        $query = $this->createQueryBuilder('h')
            ->where('h.recipe = :id');
        return $query->getResult();
    }
}
