<?php

namespace AppBundle\Repository;

/**
 * UserFollowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserFollowRepository extends \Doctrine\ORM\EntityRepository
{
}
