<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get general info for a user (username, email and registered_date)
     *
     * @param String $userId
     * @return array
     */
    public function getGeneralInfo($userId)
    {
        $query = $this->createQueryBuilder('h')
            ->select("h.username", "h.email", "h.registeredDate")
            ->where('h.userId = :userId')
            ->setParameter(':userId', $userId)
            ->getQuery();

        return $query->getResult();
    }

    /**
     * Search for related users
     *
     * @param String $searchString
     * @return array
     */
    public function searchUserByUsername($searchString)
    {
        $query = $this->createQueryBuilder('u')
            ->where('u.username LIKE :username')
            ->setParameter('username', "%$searchString%")
            ->getQuery();

        return $query->getResult();
    }

    public function getLastRegisteredUsers($maxResults) {
        $date = new \DateTime();
        $date->modify('-7 days');

        $query = $this->createQueryBuilder('u')
            ->where('u.registeredDate > :date')
            ->setParameter(':date', $date)
            ->select('COUNT(u)')
            ->getQuery();

        if ($maxResults != 0) {
            $query->setMaxResults($maxResults);
        }

        return $query->getResult();
    }
}
