<?php

namespace AppBundle\Repository;

/**
 * UserRateRecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRateRecipeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find and return average rating for a recipe
     *
     * @param int $recipeId
     * @return array
     */
    public function findRecipeAverageRating($recipeId)
    {
        $query = $this->createQueryBuilder('h')
            ->select("avg(h.rating) as rating_avg, count(h.rating) as rating_count")
            ->where('h.recipe = :id')
            ->setParameter(':id', $recipeId)
            ->getQuery();

        return $query->getResult();
    }
}
