<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getGeneralInfo($userId) {

        $query = $this->createQueryBuilder('h')
            ->select("h.username", "h.email", "h.registeredDate")
            ->where('h.userId = :userId')
            ->setParameter(':userId', $userId)
            ->getQuery();

        return $query->getResult();
    }
}
