# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app_user.image_uploader:
        class: AppBundle\Service\FileUploader
        arguments: ['%image_user_directory%']
    app_recipe.image_uploader:
        class: AppBundle\Service\FileUploader
        arguments: ['%image_recipe_directory%']
